defaultEntryPoints = ["http", "https"]
logLevel = "INFO"
RootCAs = [ "/var/acme-cert.pem" ]
InsecureSkipVerify = true

[api]
address = ":8080"
  [api.statistics]
  recentErrors = 20

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
      [entryPoints.http.redirect]
      entryPoint = "https"

  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]

      [[entryPoints.https.tls.certificates]]
      certFile = "/ssl/ssl.crt"
      keyFile = "/ssl/ssl.key"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker"
exposedbydefault = true

[accessLog]
[ping]
entryPoint = "http"
